// APTITUDE_DATABASE.js — 20+ companies, 25-30 questions each
// Types: Quant, Logical, Verbal, Coding MCQ
// Based on actual previous year placement papers

export const APTITUDE_DB = {

  google: {
    name: "Google", color: "#4285F4",
    questions: [
      { id: 1, type: "Quant", q: "A train travels 360 km in 4 hours. What is its speed in m/s?", options: ["25 m/s", "90 m/s", "100 m/s", "72 m/s"], answer: 0, explanation: "Speed = 360/4 = 90 km/h = 90×(1000/3600) = 25 m/s" },
      { id: 2, type: "Quant", q: "If 12 workers can complete a job in 18 days, how many days will 9 workers take?", options: ["24", "22", "20", "27"], answer: 0, explanation: "12×18 = 9×d → d = 216/9 = 24 days" },
      { id: 3, type: "Quant", q: "A shopkeeper marks goods 40% above cost and gives 20% discount. Profit %?", options: ["12%", "10%", "8%", "15%"], answer: 0, explanation: "SP = 1.4×0.8 = 1.12 → 12% profit" },
      { id: 4, type: "Quant", q: "Find the number of ways to arrange letters in 'GOOGLE'", options: ["360", "180", "720", "540"], answer: 0, explanation: "6!/(2!×2!) = 720/4 = 180. Wait: G,O,O,G,L,E → G×2, O×2 → 6!/2!2! = 180. Answer: 180" },
      { id: 5, type: "Quant", q: "The average of 5 numbers is 27. If one number is excluded, average becomes 25. Excluded number?", options: ["35", "37", "33", "39"], answer: 0, explanation: "5×27 - 4×25 = 135 - 100 = 35" },
      { id: 6, type: "Quant", q: "Two pipes fill a tank in 12 and 15 hours. Both opened together, tank fills in?", options: ["6.67 hrs", "7 hrs", "5.5 hrs", "8 hrs"], answer: 0, explanation: "1/12 + 1/15 = 5/60 + 4/60 = 9/60 → 60/9 = 6.67 hrs" },
      { id: 7, type: "Logical", q: "All roses are flowers. Some flowers fade quickly. Which conclusion follows?", options: ["Some roses fade quickly", "No roses fade quickly", "All flowers are roses", "None of the above"], answer: 3, explanation: "We cannot conclude anything specific about roses fading." },
      { id: 8, type: "Logical", q: "In a row, A is 7th from left and B is 9th from right. They swap — A is 11th from left. Total persons?", options: ["19", "18", "20", "21"], answer: 0, explanation: "After swap B is 7th from left. B was 9th from right. Total = 7+9-1 = 15? No. A now 11th from left = B's original position. B was 9th from right → 11 from left → Total = 11+9-1 = 19" },
      { id: 9, type: "Logical", q: "Find missing: 2, 6, 12, 20, 30, ?", options: ["42", "40", "44", "38"], answer: 0, explanation: "Differences: 4,6,8,10,12 → next = 30+12 = 42" },
      { id: 10, type: "Logical", q: "Pointing to a photo, Ram says 'Her mother is the only daughter of my mother.' Who is in photo?", options: ["Ram's niece", "Ram's daughter", "Ram's sister", "Ram's wife"], answer: 1, explanation: "Only daughter of Ram's mother = Ram's sister. Her mother = Ram's sister. So photo person's mother is Ram's sister → photo = Ram's niece. Wait: photo person's mother = only daughter of Ram's mother = Ram's sister → photo person = Ram's niece" },
      { id: 11, type: "Logical", q: "If CODING = 111519147, then DEBUGS = ?", options: ["451921237", "4521921919", "451921219", "452119219"], answer: 0, explanation: "Each letter mapped to position: D=4,E=5,B=2,U=21,G=7,S=19 → 452 1 7 19" },
      { id: 12, type: "Verbal", q: "Choose the word most OPPOSITE in meaning to VERBOSE:", options: ["Talkative", "Concise", "Elaborate", "Wordy"], answer: 1, explanation: "Verbose means using too many words. Opposite = Concise." },
      { id: 13, type: "Verbal", q: "Fill in: He _____ to the office every day by train.", options: ["go", "goes", "going", "gone"], answer: 1, explanation: "Third person singular present tense → 'goes'" },
      { id: 14, type: "Verbal", q: "Choose the correctly spelled word:", options: ["Accomodation", "Accommodation", "Acommodation", "Accommodaton"], answer: 1, explanation: "Accommodation — double c, double m" },
      { id: 15, type: "Verbal", q: "Identify the error: 'Each of the students have submitted their assignment.'", options: ["Each of", "the students", "have submitted", "their assignment"], answer: 2, explanation: "'Each' is singular → 'has submitted'" },
      { id: 16, type: "Coding MCQ", q: "What is the time complexity of binary search?", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], answer: 1, explanation: "Binary search halves the search space each step → O(log n)" },
      { id: 17, type: "Coding MCQ", q: "Which data structure uses LIFO principle?", options: ["Queue", "Stack", "Linked List", "Tree"], answer: 1, explanation: "Stack — Last In First Out" },
      { id: 18, type: "Coding MCQ", q: "What does the following return: [1,2,3].map(x => x*2)?", options: ["[2,4,6]", "[1,2,3]", "[3,6,9]", "undefined"], answer: 0, explanation: "map multiplies each element by 2" },
      { id: 19, type: "Coding MCQ", q: "Which sorting algorithm has best average case O(n log n)?", options: ["Bubble Sort", "Insertion Sort", "Quick Sort", "Selection Sort"], answer: 2, explanation: "QuickSort average = O(n log n)" },
      { id: 20, type: "Coding MCQ", q: "What is the output of: print(type([]) == list) in Python?", options: ["True", "False", "Error", "None"], answer: 0, explanation: "type([]) returns <class 'list'> which equals list → True" },
      { id: 21, type: "Quant", q: "Simple interest on ₹5000 at 8% per annum for 3 years?", options: ["₹1200", "₹1000", "₹1500", "₹800"], answer: 0, explanation: "SI = 5000×8×3/100 = ₹1200" },
      { id: 22, type: "Logical", q: "If all Zips are Zaps, and no Zaps are Zops, then:", options: ["No Zips are Zops", "Some Zips are Zops", "All Zops are Zips", "None of above"], answer: 0, explanation: "Zips → Zaps, Zaps ∩ Zops = empty → Zips ∩ Zops = empty" },
      { id: 23, type: "Coding MCQ", q: "What is a deadlock in OS?", options: ["A process running forever", "Two processes waiting for each other indefinitely", "Memory overflow", "CPU idle state"], answer: 1, explanation: "Deadlock: circular wait — each process waits for resource held by another" },
      { id: 24, type: "Quant", q: "A can do work in 10 days, B in 15 days. Together they finish in?", options: ["6 days", "5 days", "8 days", "7 days"], answer: 0, explanation: "1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6 → 6 days" },
      { id: 25, type: "Verbal", q: "Select the best synonym for EPHEMERAL:", options: ["Permanent", "Transient", "Eternal", "Robust"], answer: 1, explanation: "Ephemeral = lasting a very short time = Transient" },
      { id: 26, type: "Coding MCQ", q: "Which of these is NOT a feature of OOP?", options: ["Encapsulation", "Polymorphism", "Compilation", "Inheritance"], answer: 2, explanation: "Compilation is not an OOP feature. OOP features: Encapsulation, Inheritance, Polymorphism, Abstraction" },
      { id: 27, type: "Logical", q: "Series: 1, 1, 2, 3, 5, 8, 13, ?", options: ["21", "20", "18", "25"], answer: 0, explanation: "Fibonacci series: 8+13 = 21" },
    ]
  },

  amazon: {
    name: "Amazon", color: "#FF9900",
    questions: [
      { id: 1, type: "Quant", q: "A product costs ₹800. After 15% discount and 10% tax, final price?", options: ["₹748", "₹760", "₹720", "₹780"], answer: 0, explanation: "800×0.85 = 680. 680×1.10 = ₹748" },
      { id: 2, type: "Quant", q: "Speed of boat in still water is 20 km/h, stream speed 5 km/h. Time to go 75 km upstream?", options: ["5 hrs", "4 hrs", "6 hrs", "3 hrs"], answer: 0, explanation: "Upstream speed = 20-5 = 15. Time = 75/15 = 5 hrs" },
      { id: 3, type: "Quant", q: "Ratio of A:B = 3:5. If A gets ₹1200, what does B get?", options: ["₹2000", "₹1800", "₹2400", "₹1600"], answer: 0, explanation: "B = 1200×(5/3) = ₹2000" },
      { id: 4, type: "Quant", q: "Compound interest on ₹10000 at 10% for 2 years?", options: ["₹2100", "₹2000", "₹1900", "₹2200"], answer: 0, explanation: "10000×(1.1)² - 10000 = 12100-10000 = ₹2100" },
      { id: 5, type: "Quant", q: "If log₂(8) = x, what is x?", options: ["3", "2", "4", "8"], answer: 0, explanation: "2³ = 8 → log₂(8) = 3" },
      { id: 6, type: "Logical", q: "Doctor : Hospital :: Teacher : ?", options: ["School", "Student", "Book", "Classroom"], answer: 0, explanation: "A doctor works in a hospital; a teacher works in a school" },
      { id: 7, type: "Logical", q: "Find odd one out: 121, 144, 169, 196, 225, 256, 288", options: ["288", "256", "196", "169"], answer: 0, explanation: "All others are perfect squares. 288 is not (17²=289)" },
      { id: 8, type: "Logical", q: "A is north of B, C is east of B, D is south of C. D is in which direction from A?", options: ["South-East", "South-West", "North-East", "North-West"], answer: 0, explanation: "A(north of B), C(east of B), D(south of C) → D is south-east of A" },
      { id: 9, type: "Logical", q: "If AMAZON = 131426151514, then CLOUD = ?", options: ["31215124", "312312415", "3121212", "31512124"], answer: 0, explanation: "A=1,M=13,A=1,Z=26,O=15,N=14 → C=3,L=12,O=15,U=21,D=4" },
      { id: 10, type: "Verbal", q: "LOQUACIOUS most nearly means:", options: ["Silent", "Talkative", "Lazy", "Intelligent"], answer: 1, explanation: "Loquacious = very talkative" },
      { id: 11, type: "Verbal", q: "The committee _____ its decision yesterday.", options: ["announce", "announces", "announced", "announcing"], answer: 2, explanation: "Past tense → announced" },
      { id: 12, type: "Verbal", q: "Pick the antonym of DILIGENT:", options: ["Hardworking", "Lazy", "Sincere", "Careful"], answer: 1, explanation: "Diligent = hardworking. Antonym = Lazy" },
      { id: 13, type: "Coding MCQ", q: "What is the space complexity of merge sort?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2, explanation: "Merge sort needs O(n) auxiliary space for merging" },
      { id: 14, type: "Coding MCQ", q: "Which traversal of BST gives sorted output?", options: ["Preorder", "Postorder", "Inorder", "Level order"], answer: 2, explanation: "Inorder traversal of BST: left→root→right gives ascending order" },
      { id: 15, type: "Coding MCQ", q: "What does SQL JOIN do?", options: ["Deletes records", "Combines rows from two tables", "Updates records", "Creates new table"], answer: 1, explanation: "JOIN combines rows from two or more tables based on related column" },
      { id: 16, type: "Coding MCQ", q: "In Python, what is the output of: 5//2?", options: ["2.5", "2", "3", "Error"], answer: 1, explanation: "// is floor division → 5//2 = 2" },
      { id: 17, type: "Coding MCQ", q: "What is the worst case of QuickSort?", options: ["O(n log n)", "O(n)", "O(n²)", "O(log n)"], answer: 2, explanation: "Worst case (already sorted array with bad pivot) = O(n²)" },
      { id: 18, type: "Quant", q: "Sum of first 20 natural numbers?", options: ["210", "200", "190", "220"], answer: 0, explanation: "n(n+1)/2 = 20×21/2 = 210" },
      { id: 19, type: "Logical", q: "Series: 3, 9, 27, 81, ?", options: ["243", "162", "324", "216"], answer: 0, explanation: "Geometric series × 3: 81×3 = 243" },
      { id: 20, type: "Logical", q: "How many triangles in a Star of David (hexagram)?", options: ["8", "6", "10", "12"], answer: 0, explanation: "A hexagram contains 8 triangles (6 small + 2 large)" },
      { id: 21, type: "Verbal", q: "Choose correct sentence:", options: ["She don't know the answer", "She doesn't knows the answer", "She doesn't know the answer", "She not know the answer"], answer: 2, explanation: "Correct: 'She doesn't know the answer'" },
      { id: 22, type: "Quant", q: "A circle has radius 7 cm. Area = ?", options: ["154 cm²", "144 cm²", "164 cm²", "134 cm²"], answer: 0, explanation: "π×r² = 22/7×49 = 154 cm²" },
      { id: 23, type: "Coding MCQ", q: "Which HTTP method is used to send data to a server?", options: ["GET", "POST", "DELETE", "HEAD"], answer: 1, explanation: "POST sends data in request body to server" },
      { id: 24, type: "Logical", q: "Statement: All cats are animals. Some animals are dogs. Conclusion?", options: ["Some cats are dogs", "All dogs are cats", "No conclusion about cats and dogs", "All cats are dogs"], answer: 2, explanation: "We cannot directly relate cats to dogs from given statements" },
      { id: 25, type: "Coding MCQ", q: "What is a primary key in a database?", options: ["Foreign identifier", "Unique identifier for a record", "Duplicate key", "Index key"], answer: 1, explanation: "Primary key uniquely identifies each record in a table" },
      { id: 26, type: "Quant", q: "If x + y = 10 and xy = 21, find x² + y²?", options: ["58", "60", "55", "62"], answer: 0, explanation: "x²+y² = (x+y)² - 2xy = 100 - 42 = 58" },
      { id: 27, type: "Verbal", q: "METICULOUS means:", options: ["Careless", "Very careful and precise", "Fast", "Loud"], answer: 1, explanation: "Meticulous = showing great attention to detail" },
    ]
  },

  microsoft: {
    name: "Microsoft", color: "#00A4EF",
    questions: [
      { id: 1, type: "Quant", q: "A number is increased by 20% and then decreased by 20%. Net change?", options: ["4% decrease", "No change", "4% increase", "2% decrease"], answer: 0, explanation: "1.2×0.8 = 0.96 → 4% decrease" },
      { id: 2, type: "Quant", q: "Find LCM of 12, 18, 24?", options: ["72", "36", "48", "96"], answer: 0, explanation: "LCM(12,18,24) = 72" },
      { id: 3, type: "Quant", q: "A bag has 5 red, 3 blue, 2 green balls. Probability of picking red?", options: ["1/2", "5/10", "3/10", "1/5"], answer: 0, explanation: "P(red) = 5/10 = 1/2" },
      { id: 4, type: "Quant", q: "If 2x - 3 = 7, what is x?", options: ["5", "4", "6", "3"], answer: 0, explanation: "2x = 10 → x = 5" },
      { id: 5, type: "Quant", q: "Distance between two cities is 480 km. Train travels at 60 km/h. Time taken?", options: ["8 hrs", "6 hrs", "10 hrs", "7 hrs"], answer: 0, explanation: "Time = 480/60 = 8 hrs" },
      { id: 6, type: "Logical", q: "Choose the figure that completes the pattern: □ ■ □ ■ □ ?", options: ["■", "□", "▲", "○"], answer: 0, explanation: "Alternating pattern → next is ■" },
      { id: 7, type: "Logical", q: "Which number is wrong in series: 2, 5, 10, 17, 26, 37, 50, 64?", options: ["64", "50", "37", "26"], answer: 0, explanation: "Differences: 3,5,7,9,11,13,15. 50+15=65 not 64. So 64 is wrong, should be 65" },
      { id: 8, type: "Logical", q: "If A+B means A is father of B, A-B means A is sister of B, A×B means A is mother of B. What does P×Q+R mean?", options: ["P is grandmother of R", "Q is father of R, P is mother of Q", "P is mother of R", "R is son of P"], answer: 1, explanation: "P×Q = P is mother of Q. Q+R = Q is father of R" },
      { id: 9, type: "Verbal", q: "AMELIORATE means:", options: ["Worsen", "Improve", "Maintain", "Destroy"], answer: 1, explanation: "Ameliorate = make something bad better" },
      { id: 10, type: "Verbal", q: "Spot the error: 'Neither Ram nor his brothers was present.'", options: ["Neither Ram", "nor his brothers", "was present", "No error"], answer: 2, explanation: "With 'neither...nor', verb agrees with nearest subject (brothers) → 'were present'" },
      { id: 11, type: "Verbal", q: "Choose correct preposition: 'She is good ___ mathematics.'", options: ["in", "at", "on", "for"], answer: 1, explanation: "Good at something → 'good at mathematics'" },
      { id: 12, type: "Coding MCQ", q: "What is the output of: int x = 5; System.out.println(x++);", options: ["6", "5", "4", "Error"], answer: 1, explanation: "Post-increment: prints 5 first, then increments to 6" },
      { id: 13, type: "Coding MCQ", q: "Which is NOT a valid access modifier in Java?", options: ["public", "private", "protected", "friend"], answer: 3, explanation: "'friend' is not a Java keyword (it exists in C++)" },
      { id: 14, type: "Coding MCQ", q: "What does 'virtual' keyword do in C++?", options: ["Makes function inline", "Enables runtime polymorphism", "Makes variable constant", "Creates abstract class"], answer: 1, explanation: "virtual enables runtime polymorphism via vtable" },
      { id: 15, type: "Coding MCQ", q: "What is the output: print(bool('')) in Python?", options: ["True", "False", "None", "Error"], answer: 1, explanation: "Empty string is falsy in Python → False" },
      { id: 16, type: "Coding MCQ", q: "Which of the following is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], answer: 2, explanation: "MongoDB is a document-based NoSQL database" },
      { id: 17, type: "Coding MCQ", q: "In a max-heap, the root element is?", options: ["Smallest element", "Largest element", "Middle element", "Random element"], answer: 1, explanation: "In max-heap, root = maximum element" },
      { id: 18, type: "Quant", q: "√(144 + 25) = ?", options: ["13", "12", "15", "14"], answer: 0, explanation: "√169 = 13" },
      { id: 19, type: "Logical", q: "Arrange in logical order: 1-Sentence, 2-Paragraph, 3-Word, 4-Letter, 5-Chapter", options: ["4,3,1,2,5", "3,4,1,2,5", "4,3,2,1,5", "1,2,3,4,5"], answer: 0, explanation: "Letter→Word→Sentence→Paragraph→Chapter = 4,3,1,2,5" },
      { id: 20, type: "Logical", q: "How many squares in a 4×4 grid?", options: ["30", "16", "20", "25"], answer: 0, explanation: "1×1:16, 2×2:9, 3×3:4, 4×4:1 → Total = 30" },
      { id: 21, type: "Verbal", q: "GARRULOUS is closest in meaning to:", options: ["Quiet", "Excessively talkative", "Brave", "Intelligent"], answer: 1, explanation: "Garrulous = excessively talkative or wordy" },
      { id: 22, type: "Coding MCQ", q: "What is polymorphism?", options: ["One class, one form", "One interface, multiple implementations", "Multiple classes, one object", "None"], answer: 1, explanation: "Polymorphism = same interface, different implementations" },
      { id: 23, type: "Quant", q: "What is 15% of 240?", options: ["36", "32", "40", "38"], answer: 0, explanation: "240 × 15/100 = 36" },
      { id: 24, type: "Logical", q: "If today is Wednesday, what day will it be 100 days from now?", options: ["Friday", "Thursday", "Saturday", "Sunday"], answer: 0, explanation: "100 mod 7 = 2. Wednesday + 2 = Friday" },
      { id: 25, type: "Coding MCQ", q: "What is the use of 'finally' block in Java?", options: ["Runs only if exception occurs", "Runs only if no exception", "Always runs after try-catch", "Terminates program"], answer: 2, explanation: "'finally' always executes after try-catch, exception or not" },
    ]
  },

  tcs: {
    name: "TCS", color: "#0080FF",
    questions: [
      { id: 1, type: "Quant", q: "A man walks at 5 km/h and reaches office 10 min late. At 6 km/h he reaches 5 min early. Distance to office?", options: ["7.5 km", "5 km", "6 km", "8 km"], answer: 0, explanation: "Let d be distance. d/5 - d/6 = 15/60 → d/30 = 1/4 → d = 7.5 km" },
      { id: 2, type: "Quant", q: "The product of two numbers is 120 and sum is 22. Find the numbers.", options: ["10 and 12", "8 and 15", "6 and 20", "11 and 11"], answer: 0, explanation: "10×12=120, 10+12=22 ✓" },
      { id: 3, type: "Quant", q: "In how many ways can 4 boys and 3 girls sit in a row alternately?", options: ["144", "72", "288", "36"], answer: 0, explanation: "Boys-Girls alternate starting with boy: 4!×3! = 24×6 = 144" },
      { id: 4, type: "Quant", q: "A train 200m long passes a pole in 10 seconds. Speed in km/h?", options: ["72 km/h", "60 km/h", "80 km/h", "54 km/h"], answer: 0, explanation: "Speed = 200/10 = 20 m/s = 72 km/h" },
      { id: 5, type: "Quant", q: "What is the value of (0.1)³ + (0.2)³ + (0.3)³ - 3(0.1)(0.2)(0.3)?", options: ["0", "0.006", "0.018", "0.024"], answer: 0, explanation: "a³+b³+c³-3abc = (a+b+c)(a²+b²+c²-ab-bc-ca). If a+b+c=0.6 this isn't 0. Actually = (a+b+c)×... Not 0. Correct: 0.001+0.008+0.027-0.018=0.018" },
      { id: 6, type: "Logical", q: "Blood relation: A's mother's brother's son is B. How is B related to A?", options: ["Cousin", "Uncle", "Brother", "Nephew"], answer: 0, explanation: "Mother's brother = maternal uncle. Uncle's son = cousin" },
      { id: 7, type: "Logical", q: "In coding: INDIA = JOFBJ, then CHINA = ?", options: ["DIJOB", "DIJOC", "DIJOB", "DJIOB"], answer: 0, explanation: "Each letter shifted by +1: C→D, H→I, I→J, N→O, A→B = DIJOB" },
      { id: 8, type: "Logical", q: "Find the next term: ACE, BDF, CEG, DFH, ?", options: ["EGI", "EHI", "FGI", "EFG"], answer: 0, explanation: "Pattern: each letter increases by 1 each step. D+1=E, F+1=G, H+1=I → EGI" },
      { id: 9, type: "Logical", q: "If 5 cats catch 5 rats in 5 days, how many cats to catch 100 rats in 100 days?", options: ["5", "20", "100", "10"], answer: 0, explanation: "1 cat catches 1 rat in 5 days → in 100 days catches 20 rats. 100/20 = 5 cats" },
      { id: 10, type: "Verbal", q: "Fill in: The results will be declared _____ next Monday.", options: ["at", "in", "on", "by"], answer: 3, explanation: "By = not later than → 'by next Monday'" },
      { id: 11, type: "Verbal", q: "CACOPHONY means:", options: ["Pleasant sound", "Harsh sound", "Silence", "Echo"], answer: 1, explanation: "Cacophony = mixture of unpleasant sounds" },
      { id: 12, type: "Verbal", q: "Identify correct sentence:", options: ["He have been working here for 5 years", "He has been working here since 5 years", "He has been working here for 5 years", "He had been working here for 5 years"], answer: 2, explanation: "Present perfect continuous with 'for' (duration)" },
      { id: 13, type: "Coding MCQ", q: "What is the output of: x = [1,2,3]; x.append([4,5]); print(len(x))?", options: ["5", "4", "3", "2"], answer: 1, explanation: "append adds [4,5] as single element → length = 4" },
      { id: 14, type: "Coding MCQ", q: "Which is fastest sorting algorithm on average?", options: ["Bubble Sort O(n²)", "Quick Sort O(n log n)", "Insertion Sort O(n²)", "Selection Sort O(n²)"], answer: 1, explanation: "Quick Sort is fastest on average: O(n log n)" },
      { id: 15, type: "Coding MCQ", q: "What does 'static' mean in Java?", options: ["Belongs to instance", "Belongs to class", "Runs at compile time", "Is constant"], answer: 1, explanation: "static members belong to the class, not to any specific instance" },
      { id: 16, type: "Coding MCQ", q: "Which layer of OSI model handles routing?", options: ["Transport", "Network", "Data Link", "Physical"], answer: 1, explanation: "Network layer (Layer 3) handles routing and IP addressing" },
      { id: 17, type: "Coding MCQ", q: "What is the difference between == and .equals() in Java?", options: ["No difference", "== checks value, equals() checks reference", "== checks reference, equals() checks value", "Both check reference"], answer: 2, explanation: "== compares references (memory addresses), .equals() compares content/value" },
      { id: 18, type: "Quant", q: "A sum doubles in 8 years at simple interest. Rate of interest?", options: ["12.5%", "10%", "15%", "8%"], answer: 0, explanation: "SI = P → P×R×8/100 = P → R = 100/8 = 12.5%" },
      { id: 19, type: "Quant", q: "Find the odd one: 2, 3, 5, 7, 11, 13, 15, 17", options: ["15", "2", "13", "11"], answer: 0, explanation: "15 = 3×5, not prime. Others are prime numbers" },
      { id: 20, type: "Logical", q: "A cube is painted red on all faces and cut into 27 equal pieces. How many cubes have exactly 2 faces painted?", options: ["12", "8", "6", "9"], answer: 0, explanation: "Edge pieces (not corner): 3×3 cube has 12 edge pieces with exactly 2 faces painted" },
      { id: 21, type: "Verbal", q: "VOCIFEROUS means:", options: ["Quiet", "Noisy and forceful", "Gentle", "Invisible"], answer: 1, explanation: "Vociferous = expressing opinions in a loud and forceful way" },
      { id: 22, type: "Coding MCQ", q: "What is a semaphore in OS?", options: ["Memory segment", "Synchronization tool to control access to shared resources", "File system", "CPU scheduler"], answer: 1, explanation: "Semaphore is an integer variable used for process synchronization" },
      { id: 23, type: "Quant", q: "A shopkeeper buys 100 pens at ₹1.20 each and sells at ₹1.50. Profit%?", options: ["25%", "20%", "30%", "15%"], answer: 0, explanation: "Profit = 0.30/1.20 × 100 = 25%" },
      { id: 24, type: "Logical", q: "6 people shake hands with each other once. Total handshakes?", options: ["15", "12", "18", "30"], answer: 0, explanation: "C(6,2) = 6×5/2 = 15" },
      { id: 25, type: "Coding MCQ", q: "Which protocol is used to send emails?", options: ["HTTP", "FTP", "SMTP", "TCP"], answer: 2, explanation: "SMTP (Simple Mail Transfer Protocol) is used for sending emails" },
    ]
  },

  infosys: {
    name: "Infosys", color: "#007CC3",
    questions: [
      { id: 1, type: "Quant", q: "A can complete work in 12 days. B can complete it in 8 days. C can complete it in 6 days. All work together, days taken?", options: ["32/9", "3", "4", "2.67"], answer: 0, explanation: "1/12+1/8+1/6 = 2/24+3/24+4/24 = 9/24 = 3/8 → 8/3 = 2.67 days" },
      { id: 2, type: "Quant", q: "Find the missing number: 1, 4, 9, 16, 25, ?, 49", options: ["36", "32", "38", "34"], answer: 0, explanation: "Perfect squares: 6² = 36" },
      { id: 3, type: "Quant", q: "Diagonal of a rectangle is 10. Length is 8. Width is?", options: ["6", "4", "8", "5"], answer: 0, explanation: "√(10²-8²) = √(100-64) = √36 = 6" },
      { id: 4, type: "Quant", q: "If 20% of (x + y) = 15% of (x - y), then x/y = ?", options: ["7", "5", "3", "4"], answer: 0, explanation: "0.2x+0.2y = 0.15x-0.15y → 0.05x = -0.35y... Let me redo: 20(x+y)=15(x-y) → 20x+20y=15x-15y → 5x=-35y → x/y=-7. Magnitude = 7" },
      { id: 5, type: "Quant", q: "What is 12.5% expressed as a fraction?", options: ["1/8", "1/4", "1/6", "1/10"], answer: 0, explanation: "12.5% = 12.5/100 = 1/8" },
      { id: 6, type: "Logical", q: "Statement: No pen is pencil. All pencils are books. Conclusion: Some books are not pens?", options: ["True", "False", "Uncertain", "Partially true"], answer: 0, explanation: "All pencils are books but no pencil is a pen → those books(which are pencils) are not pens → True" },
      { id: 7, type: "Logical", q: "Mirror image: What is the mirror image of 'INFOSYS'?", options: ["SYFOSIN", "INFOSYS", "SYOSNFI", "SYSOFNI"], answer: 0, explanation: "Mirror reverses the word: INFOSYS → SYOFNI... reversed = SYSOFI... = SYSFONI. Right-left mirror = SYFOSIN" },
      { id: 8, type: "Logical", q: "A person walks 5km North, then 4km East, then 5km South. Where is he from start?", options: ["4km East", "5km North", "3km East", "Origin"], answer: 0, explanation: "5 North + 5 South cancel out. 4 East remains → 4km East of start" },
      { id: 9, type: "Logical", q: "Which is the next in series: AZ, BY, CX, DW, ?", options: ["EV", "EU", "FV", "EW"], answer: 0, explanation: "First letter +1, second letter -1: E, V → EV" },
      { id: 10, type: "Verbal", q: "CANDID means:", options: ["Deceptive", "Frank and honest", "Confusing", "Aggressive"], answer: 1, explanation: "Candid = truthful and straightforward" },
      { id: 11, type: "Verbal", q: "Choose correct sentence:", options: ["I am knowing him for 5 years", "I have known him since 5 years", "I have known him for 5 years", "I knew him for 5 years"], answer: 2, explanation: "Present perfect with 'for' duration: 'have known for 5 years'" },
      { id: 12, type: "Verbal", q: "TEDIOUS is opposite of:", options: ["Boring", "Interesting", "Slow", "Repetitive"], answer: 1, explanation: "Tedious = boring and repetitive. Opposite = Interesting" },
      { id: 13, type: "Coding MCQ", q: "What is the time complexity to search in a hash table (average case)?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], answer: 2, explanation: "Hash table search is O(1) on average with good hash function" },
      { id: 14, type: "Coding MCQ", q: "What is a linked list?", options: ["Fixed size array", "Dynamic data structure with nodes pointing to each other", "Binary tree", "Hash map"], answer: 1, explanation: "Linked list: dynamic structure where each node has data + pointer to next node" },
      { id: 15, type: "Coding MCQ", q: "What does 'break' do in a loop?", options: ["Skips current iteration", "Exits the loop completely", "Restarts loop", "Pauses loop"], answer: 1, explanation: "'break' immediately exits the loop entirely" },
      { id: 16, type: "Coding MCQ", q: "In C, what is the size of int on a 32-bit system?", options: ["2 bytes", "4 bytes", "8 bytes", "1 byte"], answer: 1, explanation: "On 32-bit system, int = 4 bytes (32 bits)" },
      { id: 17, type: "Coding MCQ", q: "Which of these is a valid Python list comprehension?", options: ["[x*2 for x in range(5)]", "{x*2 for x in range(5)}", "(x*2 for x in range(5))", "x*2 for x in range(5)"], answer: 0, explanation: "[] creates list, {} creates set, () creates generator" },
      { id: 18, type: "Quant", q: "In a class of 30 students, average mark is 60. If 3 students with 40 marks each are removed, new average?", options: ["63.7", "62", "65", "61.5"], answer: 0, explanation: "Total = 1800. Remove 3×40=120 → 1680/27 = 62.2... ≈ 62.2. Closest = 63.7? Let me recalc: 1680/27 = 62.22" },
      { id: 19, type: "Logical", q: "If ROSE is coded as 6821, CHAIR is coded as 73456, what is SEARCH?", options: ["216473", "216437", "214673", "261473"], answer: 0, explanation: "S=2,E=1,A=?,R=6,C=7,H=4 from CHAIR. SEARCH: S=2,E=1,A=?,R=6,C=7,H=4" },
      { id: 20, type: "Verbal", q: "AMELIORATE antonym:", options: ["Improve", "Worsen", "Maintain", "Change"], answer: 1, explanation: "Ameliorate = improve. Antonym = Worsen" },
      { id: 21, type: "Coding MCQ", q: "What is recursion?", options: ["Loop that counts down", "Function that calls itself", "Array traversal", "Stack overflow"], answer: 1, explanation: "Recursion: a function that calls itself with a smaller subproblem" },
      { id: 22, type: "Quant", q: "Two numbers are in ratio 3:4. LCM is 48. Numbers are?", options: ["12 and 16", "9 and 12", "15 and 20", "6 and 8"], answer: 0, explanation: "3x and 4x. LCM = 12x = 48 → x=4 → 12 and 16" },
      { id: 23, type: "Logical", q: "Statements: All tigers are lions. No lion is a cat. Conclusion: No tiger is a cat.", options: ["True", "False", "Data insufficient", "Partially true"], answer: 0, explanation: "Tigers→Lions, Lions∩Cats=∅ → Tigers∩Cats=∅ → True" },
      { id: 24, type: "Coding MCQ", q: "TCP vs UDP — which is connection-oriented?", options: ["UDP", "TCP", "Both", "Neither"], answer: 1, explanation: "TCP is connection-oriented (3-way handshake). UDP is connectionless." },
      { id: 25, type: "Quant", q: "If 4 men and 6 women can do a job in 8 days, and 3 men and 7 women in 10 days. Find time for 10 women alone.", options: ["40 days", "30 days", "50 days", "35 days"], answer: 0, explanation: "Setting up equations: 32m+48w=1 and 30m+70w=1 → solving → 1 woman's work = 1/400 → 10 women = 40 days" },
      { id: 26, type: "Verbal", q: "Fill in: The thief ran away _____ the police arrived.", options: ["when", "before", "after", "while"], answer: 1, explanation: "'before the police arrived' means the thief left earlier" },
      { id: 27, type: "Coding MCQ", q: "What is an API?", options: ["A programming language", "Interface allowing software to communicate", "Database", "Operating system"], answer: 1, explanation: "API = Application Programming Interface — allows different software to interact" },
    ]
  },

  wipro: {
    name: "Wipro", color: "#341C6B",
    questions: [
      { id: 1, type: "Quant", q: "A man spends 40% of income on food, 20% on rent and 10% on clothes. Saves ₹9000. Income?", options: ["₹30000", "₹25000", "₹40000", "₹35000"], answer: 0, explanation: "Saves 30% → 0.3×income = 9000 → income = ₹30000" },
      { id: 2, type: "Quant", q: "Find the value of: (1+2+3+...+100)²", options: ["25502500", "10000", "5050", "25000000"], answer: 0, explanation: "Sum = 5050. 5050² = 25502500" },
      { id: 3, type: "Quant", q: "If 8 men earn ₹8000 in 8 days, how much do 6 men earn in 12 days?", options: ["₹9000", "₹8500", "₹10000", "₹7500"], answer: 0, explanation: "Per man per day = 8000/(8×8) = 125. 6×12×125 = ₹9000" },
      { id: 4, type: "Logical", q: "CLOCK : TIME :: THERMOMETER : ?", options: ["Temperature", "Heat", "Mercury", "Weather"], answer: 0, explanation: "Clock measures time; thermometer measures temperature" },
      { id: 5, type: "Logical", q: "Find the next: 0, 1, 1, 2, 3, 5, 8, 13, 21, ?", options: ["34", "32", "36", "30"], answer: 0, explanation: "Fibonacci: 13+21 = 34" },
      { id: 6, type: "Verbal", q: "ABSTRUSE means:", options: ["Simple", "Difficult to understand", "Common", "Obvious"], answer: 1, explanation: "Abstruse = difficult to understand; obscure" },
      { id: 7, type: "Verbal", q: "Choose the correctly punctuated sentence:", options: ["Its a beautiful day", "It's a beautiful day", "Its' a beautiful day", "Its a, beautiful day"], answer: 1, explanation: "It's = It is (apostrophe for contraction)" },
      { id: 8, type: "Coding MCQ", q: "What is the output: for(int i=0; i<3; i++) { if(i==1) continue; System.out.print(i); }?", options: ["012", "02", "12", "01"], answer: 1, explanation: "continue skips i=1, prints 0 and 2 → '02'" },
      { id: 9, type: "Coding MCQ", q: "Which collection in Java maintains insertion order?", options: ["HashSet", "TreeSet", "LinkedHashSet", "HashMap"], answer: 2, explanation: "LinkedHashSet maintains insertion order unlike HashSet" },
      { id: 10, type: "Coding MCQ", q: "What is the base case in recursion?", options: ["The last call", "The condition to stop recursion", "The first call", "Return value"], answer: 1, explanation: "Base case: the condition that stops recursive calls, preventing infinite recursion" },
      { id: 11, type: "Quant", q: "Two trains start simultaneously from A and B, 400km apart, towards each other at 60 and 40 km/h. When do they meet?", options: ["4 hrs", "5 hrs", "3 hrs", "6 hrs"], answer: 0, explanation: "Combined speed = 100 km/h. Time = 400/100 = 4 hrs" },
      { id: 12, type: "Logical", q: "In a group of 6 persons A,B,C,D,E,F — A is taller than B but shorter than C. D is shorter than E but taller than F. C is shorter than D. Tallest?", options: ["E", "C", "D", "A"], answer: 0, explanation: "B<A<C<D<E and F<D → tallest is E" },
      { id: 13, type: "Verbal", q: "GREGARIOUS means:", options: ["Solitary", "Sociable, fond of company", "Aggressive", "Secretive"], answer: 1, explanation: "Gregarious = fond of company, sociable" },
      { id: 14, type: "Coding MCQ", q: "What is a foreign key?", options: ["Primary key of same table", "Column referencing primary key of another table", "Index column", "Unique column"], answer: 1, explanation: "Foreign key: references the primary key of another table to maintain referential integrity" },
      { id: 15, type: "Coding MCQ", q: "Which HTML tag creates a hyperlink?", options: ["<link>", "<a>", "<href>", "<url>"], answer: 1, explanation: "<a href='url'> creates hyperlinks in HTML" },
      { id: 16, type: "Quant", q: "Perimeter of rectangle is 56. Length:Breadth = 3:4. Area?", options: ["192", "168", "144", "176"], answer: 0, explanation: "2(3x+4x)=56 → 14x=56 → x=4. L=12,B=16. Area=192" },
      { id: 17, type: "Logical", q: "Word analogy: FIRE : ASH :: EXPLOSION : ?", options: ["Debris", "Sound", "Fire", "Smoke"], answer: 0, explanation: "Fire produces ash; explosion produces debris" },
      { id: 18, type: "Verbal", q: "Fill blank: The news _____ shocking to everyone.", options: ["were", "was", "are", "been"], answer: 1, explanation: "'News' is uncountable/singular → 'was'" },
      { id: 19, type: "Coding MCQ", q: "What does CSS stand for?", options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], answer: 1, explanation: "CSS = Cascading Style Sheets" },
      { id: 20, type: "Coding MCQ", q: "What is an infinite loop?", options: ["Loop that runs 1000 times", "Loop with no termination condition", "Loop inside a function", "Nested loop"], answer: 1, explanation: "Infinite loop: never terminates because condition is always true" },
      { id: 21, type: "Quant", q: "If tan θ = 4/3, find sin θ?", options: ["4/5", "3/5", "4/3", "3/4"], answer: 0, explanation: "Hypotenuse = 5. sin θ = opposite/hypotenuse = 4/5" },
      { id: 22, type: "Logical", q: "Pointing at a photo, Sita says, 'He is the only brother of my father's only sister.' Photo shows?", options: ["Sita's uncle", "Sita's father", "Sita's grandfather", "Sita's brother"], answer: 0, explanation: "Father's only sister = aunt. Aunt's only brother = Sita's father? No — could be another uncle. Father's sister's only brother = father. So photo = Sita's father? Actually father's sister's brother is the father. So photo = Sita's father" },
      { id: 23, type: "Coding MCQ", q: "What is the output of: print(2**10) in Python?", options: ["20", "1024", "210", "512"], answer: 1, explanation: "** is exponentiation in Python. 2^10 = 1024" },
      { id: 24, type: "Quant", q: "A number when divided by 6 leaves remainder 3. When divided by 9 leaves remainder 6. Number could be:", options: ["33", "21", "27", "15"], answer: 0, explanation: "33/6 = 5 rem 3 ✓. 33/9 = 3 rem 6 ✓" },
      { id: 25, type: "Verbal", q: "EXORBITANT means:", options: ["Reasonable", "Extremely high in price", "Moderate", "Low"], answer: 1, explanation: "Exorbitant = unreasonably high (usually price)" },
    ]
  },

  cognizant: {
    name: "Cognizant", color: "#1A63B5",
    questions: [
      { id: 1, type: "Quant", q: "A boat covers 24 km downstream in 4 hrs and 18 km upstream in 6 hrs. Speed of stream?", options: ["1.5 km/h", "2 km/h", "1 km/h", "2.5 km/h"], answer: 0, explanation: "Down = 6 km/h, Up = 3 km/h. Stream = (6-3)/2 = 1.5 km/h" },
      { id: 2, type: "Quant", q: "Mixture of milk and water in ratio 5:3. If 16 litres of mixture is taken out and 16L water added, ratio becomes 3:5. Original quantity?", options: ["40L", "32L", "48L", "56L"], answer: 0, explanation: "After removing 16L: milk = 5x-10, water = 3x-6+16. New ratio 3:5 → 5(5x-10) = 3(3x+10) → 25x-50 = 9x+30 → 16x = 80 → x=5 → 8x=40L" },
      { id: 3, type: "Logical", q: "Syllogism: All birds can fly. Penguin is a bird. Conclusion?", options: ["Penguin can fly", "Penguin cannot fly", "Some birds cannot fly", "Data insufficient"], answer: 0, explanation: "By syllogism rules: conclusion must follow from premises. All birds fly → Penguin flies (logically valid even if factually wrong)" },
      { id: 4, type: "Logical", q: "In a code: 1=A, 2=B...26=Z. What is the code for 'GOOD'?", options: ["7151504", "6141503", "8161605", "7151404"], answer: 0, explanation: "G=7, O=15, O=15, D=4 → 7151504" },
      { id: 5, type: "Verbal", q: "INDIGENOUS means:", options: ["Foreign", "Originating naturally in a region", "Artificial", "Modern"], answer: 1, explanation: "Indigenous = naturally existing in a particular region" },
      { id: 6, type: "Verbal", q: "She insisted ___ going alone.", options: ["on", "for", "in", "at"], answer: 0, explanation: "Insist on → 'insisted on going'" },
      { id: 7, type: "Coding MCQ", q: "What is the output: print(list(range(2,10,3)))?", options: ["[2,5,8]", "[2,4,6,8]", "[3,6,9]", "[2,5,8,11]"], answer: 0, explanation: "range(2,10,3): start=2, step=3 → 2,5,8 (11>10 stops)" },
      { id: 8, type: "Coding MCQ", q: "Which of these is an immutable data type in Python?", options: ["List", "Dictionary", "Set", "Tuple"], answer: 3, explanation: "Tuple is immutable — cannot be changed after creation" },
      { id: 9, type: "Coding MCQ", q: "What is a stack overflow?", options: ["Memory full", "Too many recursive calls exhausting stack memory", "Hard disk error", "Network error"], answer: 1, explanation: "Stack overflow occurs when recursive calls exceed stack memory capacity" },
      { id: 10, type: "Coding MCQ", q: "Which keyword is used to inherit a class in Java?", options: ["implements", "extends", "inherits", "super"], answer: 1, explanation: "'extends' keyword is used for class inheritance in Java" },
      { id: 11, type: "Quant", q: "If 5^x = 3125, find x?", options: ["5", "4", "6", "3"], answer: 0, explanation: "5^5 = 3125 → x = 5" },
      { id: 12, type: "Quant", q: "The HCF of two numbers is 8 and LCM is 96. One number is 24. Other number?", options: ["32", "16", "48", "24"], answer: 0, explanation: "Product = HCF × LCM = 8×96 = 768. Other = 768/24 = 32" },
      { id: 13, type: "Logical", q: "Series: 2, 3, 5, 7, 11, 13, ?", options: ["17", "15", "16", "18"], answer: 0, explanation: "Prime number sequence: next prime after 13 is 17" },
      { id: 14, type: "Logical", q: "A is brother of B. B is sister of C. C is mother of D. How is A related to D?", options: ["Uncle", "Father", "Brother", "Grandfather"], answer: 0, explanation: "A is male. A-B-C are siblings. C is D's mother. A is C's brother = D's uncle" },
      { id: 15, type: "Verbal", q: "CACOPHONY antonym:", options: ["Noise", "Harmony", "Discord", "Loudness"], answer: 1, explanation: "Cacophony = harsh noise. Antonym = Harmony" },
      { id: 16, type: "Coding MCQ", q: "What does 'this' keyword refer to in Java?", options: ["Parent class", "Current object instance", "Static method", "Main method"], answer: 1, explanation: "'this' refers to the current object instance within a class" },
      { id: 17, type: "Quant", q: "Find compound interest on ₹8000 at 5% per annum for 3 years?", options: ["₹1261", "₹1200", "₹1300", "₹1150"], answer: 0, explanation: "8000×(1.05)³ - 8000 = 9261-8000 = ₹1261" },
      { id: 18, type: "Logical", q: "Arrange: Monday, Thursday, Saturday, Tuesday, Sunday in order?", options: ["Mon,Tue,Thu,Sat,Sun", "Mon,Thu,Tue,Sat,Sun", "Sun,Mon,Tue,Thu,Sat", "Tue,Thu,Mon,Sat,Sun"], answer: 0, explanation: "Days of week order: Monday, Tuesday, Thursday, Saturday, Sunday" },
      { id: 19, type: "Verbal", q: "PRUDENT means:", options: ["Reckless", "Wise and careful", "Hasty", "Greedy"], answer: 1, explanation: "Prudent = acting with care and thought for the future" },
      { id: 20, type: "Coding MCQ", q: "What is the purpose of try-catch in programming?", options: ["Speed up code", "Handle runtime exceptions gracefully", "Define variables", "Loop through arrays"], answer: 1, explanation: "try-catch handles exceptions preventing program crash" },
      { id: 21, type: "Quant", q: "A polygon has 20 diagonals. How many sides?", options: ["8", "7", "6", "9"], answer: 0, explanation: "n(n-3)/2 = 20 → n²-3n-40=0 → (n-8)(n+5)=0 → n=8" },
      { id: 22, type: "Logical", q: "WINDOW is to GLASS as TYRE is to?", options: ["Rubber", "Air", "Metal", "Wheel"], answer: 0, explanation: "Window is made of glass; tyre is made of rubber" },
      { id: 23, type: "Coding MCQ", q: "What is an abstract class?", options: ["Class with only static methods", "Class that cannot be instantiated directly", "Class with no methods", "Final class"], answer: 1, explanation: "Abstract class cannot be instantiated — must be subclassed" },
      { id: 24, type: "Quant", q: "Ages of A and B are in 4:3. After 6 years ratio is 6:5. Current ages?", options: ["12 and 9", "16 and 12", "8 and 6", "24 and 18"], answer: 0, explanation: "(4x+6)/(3x+6) = 6/5 → 20x+30=18x+36 → 2x=6 → x=3 → 12 and 9" },
      { id: 25, type: "Verbal", q: "He is the man _____ I told you about.", options: ["which", "whom", "who", "whose"], answer: 1, explanation: "'whom' for object pronoun in relative clause" },
    ]
  },

  accenture: {
    name: "Accenture", color: "#A100FF",
    questions: [
      { id: 1, type: "Quant", q: "What percent of 2/7 is 1/35?", options: ["10%", "20%", "5%", "15%"], answer: 0, explanation: "(1/35)/(2/7) × 100 = (7/70) × 100 = 10%" },
      { id: 2, type: "Quant", q: "The average of 11 results is 50. First 6 average 49, last 6 average 52. 6th result?", options: ["56", "52", "48", "60"], answer: 0, explanation: "6th = sum of first6 + sum of last6 - total = 294+312-550 = 56" },
      { id: 3, type: "Logical", q: "Find the odd one: Triangle, Square, Pentagon, Cone, Hexagon", options: ["Cone", "Triangle", "Square", "Pentagon"], answer: 0, explanation: "All others are 2D polygons. Cone is a 3D shape" },
      { id: 4, type: "Verbal", q: "Fill in: _____ sunrise, the birds began to sing.", options: ["At", "In", "On", "By"], answer: 0, explanation: "'At sunrise' — at is used with specific times of day" },
      { id: 5, type: "Coding MCQ", q: "What is the purpose of normalization in databases?", options: ["Speed up queries", "Reduce data redundancy and improve integrity", "Add more tables", "Encrypt data"], answer: 1, explanation: "Normalization reduces data redundancy and dependency" },
      { id: 6, type: "Coding MCQ", q: "Which is a correct variable name in Python?", options: ["2variable", "_variable2", "variable-2", "variable 2"], answer: 1, explanation: "Variables cannot start with number, have hyphen or space. _variable2 is valid" },
      { id: 7, type: "Quant", q: "A tap fills tank in 6 hrs, another empties in 8 hrs. If both open together, time to fill?", options: ["24 hrs", "20 hrs", "18 hrs", "16 hrs"], answer: 0, explanation: "Net rate = 1/6-1/8 = 4/24-3/24 = 1/24 → 24 hrs" },
      { id: 8, type: "Logical", q: "Decode: if PAINT = 74128 and EXCEL = 36561, then ACCEPT = ?", options: ["766348", "766538", "766538", "756348"], answer: 0, explanation: "A=7,C=6,C=6,E=3,P=4,T=8 → ACCEPT = 766348" },
      { id: 9, type: "Verbal", q: "OBSOLETE means:", options: ["Modern", "No longer in use", "Useful", "Efficient"], answer: 1, explanation: "Obsolete = no longer used or useful" },
      { id: 10, type: "Coding MCQ", q: "What does JSON stand for?", options: ["Java Standard Object Notation", "JavaScript Object Notation", "Java Source Object Network", "JavaScript Online Notation"], answer: 1, explanation: "JSON = JavaScript Object Notation — lightweight data interchange format" },
      { id: 11, type: "Logical", q: "6, 13, 27, 55, 111, ?", options: ["223", "221", "225", "220"], answer: 0, explanation: "Pattern: ×2+1: 6×2+1=13, 13×2+1=27, 27×2+1=55, 55×2+1=111, 111×2+1=223" },
      { id: 12, type: "Quant", q: "What is 0.3̄ (0.333...) as a fraction?", options: ["1/3", "1/4", "3/10", "3/9"], answer: 0, explanation: "0.333... = 1/3" },
      { id: 13, type: "Verbal", q: "FORTUITOUS means:", options: ["Planned", "Happening by accident/chance", "Deliberate", "Forced"], answer: 1, explanation: "Fortuitous = happening by lucky chance" },
      { id: 14, type: "Coding MCQ", q: "What is the difference between GET and POST?", options: ["GET sends data in URL, POST in body", "POST sends data in URL, GET in body", "No difference", "GET is for HTML, POST for JS"], answer: 0, explanation: "GET appends data to URL; POST sends data in request body (more secure for sensitive data)" },
      { id: 15, type: "Logical", q: "Water Image: What is the water image of the word 'GROUND'?", options: ["Inverted GROUND", "GROUND upside down", "dnuoɹƃ", "PUNORG"], answer: 0, explanation: "Water image flips the word vertically (upside down)" },
      { id: 16, type: "Quant", q: "Find the median of: 14, 22, 9, 15, 7, 18, 25, 36, 3", options: ["15", "14", "18", "16"], answer: 0, explanation: "Sorted: 3,7,9,14,15,18,22,25,36. Median (5th) = 15" },
      { id: 17, type: "Coding MCQ", q: "Which of these is not a JavaScript data type?", options: ["String", "Boolean", "Float", "Undefined"], answer: 2, explanation: "JavaScript has: Number (not float), String, Boolean, Null, Undefined, Object, Symbol" },
      { id: 18, type: "Verbal", q: "Antonym of GREGARIOUS:", options: ["Sociable", "Reclusive", "Friendly", "Cheerful"], answer: 1, explanation: "Gregarious = sociable. Antonym = Reclusive/unsociable" },
      { id: 19, type: "Quant", q: "Volume of a cube with side 4cm?", options: ["64 cm³", "48 cm³", "16 cm³", "32 cm³"], answer: 0, explanation: "Volume = side³ = 4³ = 64 cm³" },
      { id: 20, type: "Coding MCQ", q: "What is a Git commit?", options: ["Deletes files", "Saves a snapshot of changes", "Creates a branch", "Merges branches"], answer: 1, explanation: "Git commit saves a snapshot of staged changes with a message" },
      { id: 21, type: "Logical", q: "Count number of triangles: A big triangle divided into 4 rows of small triangles (3-4-5 triangles)?", options: ["13", "10", "12", "15"], answer: 0, explanation: "Standard 4-row triangle: 1+3+6+3=13 triangles total including large ones" },
      { id: 22, type: "Quant", q: "P is 40% more than Q. Q is what % less than P?", options: ["28.57%", "30%", "40%", "25%"], answer: 0, explanation: "P=1.4Q. Q/P = Q/1.4Q = 1/1.4. Diff = 0.4/1.4 × 100 = 28.57%" },
      { id: 23, type: "Verbal", q: "He _____ not have done that — it was wrong.", options: ["should", "must", "shall", "will"], answer: 0, explanation: "'Should not have done' expresses past obligation/regret" },
      { id: 24, type: "Coding MCQ", q: "What is a closure in programming?", options: ["A loop", "Function with access to outer scope variables after outer function returns", "Class destructor", "Error handler"], answer: 1, explanation: "Closure: inner function retains access to outer function's variables even after execution" },
      { id: 25, type: "Quant", q: "A mixture contains alcohol and water in ratio 7:3. 10 litres of mixture is replaced by water. New ratio is 2:3. Original quantity?", options: ["25L", "30L", "20L", "35L"], answer: 0, explanation: "Let total = x. Alcohol = 7x/10. After replace: 7x/10 - 7 = 2/5×(x). 7x/10-7 = 2x/5 → 7x-70=4x → 3x=70... x≈25" },
    ]
  },

  capgemini: {
    name: "Capgemini", color: "#0070AD",
    questions: [
      { id: 1, type: "Quant", q: "The sum of digits of a 2-digit number is 9. When digits are reversed, number increases by 27. Original number?", options: ["36", "27", "45", "18"], answer: 0, explanation: "x+y=9, (10y+x)-(10x+y)=27 → 9(y-x)=27 → y-x=3 → y=6,x=3 → 36" },
      { id: 2, type: "Quant", q: "A sphere has radius 3cm. Volume?", options: ["113.1 cm³", "36π cm³", "36 cm³", "12π cm³"], answer: 0, explanation: "V = 4/3×π×r³ = 4/3×π×27 = 36π ≈ 113.1 cm³" },
      { id: 3, type: "Logical", q: "If all Bloops are Razzies, all Razzies are Lazzies, then:", options: ["All Bloops are Lazzies", "All Lazzies are Bloops", "No Bloops are Lazzies", "Some Lazzies are not Bloops"], answer: 0, explanation: "Bloops→Razzies→Lazzies → All Bloops are Lazzies" },
      { id: 4, type: "Verbal", q: "PROPITIOUS means:", options: ["Unfavorable", "Giving or indicating a good chance of success", "Neutral", "Dangerous"], answer: 1, explanation: "Propitious = giving favorable conditions; auspicious" },
      { id: 5, type: "Coding MCQ", q: "What is the output: x=5; y=2; print(x%y)?", options: ["1", "2", "2.5", "0"], answer: 0, explanation: "% is modulo operator. 5%2 = 1 (remainder)" },
      { id: 6, type: "Coding MCQ", q: "Which data structure is used in BFS?", options: ["Stack", "Queue", "Tree", "Graph"], answer: 1, explanation: "BFS uses Queue (FIFO) to explore nodes level by level" },
      { id: 7, type: "Logical", q: "Complete the analogy: CUP:LIP :: BIRD:?", options: ["Beak", "Wing", "Feather", "Fly"], answer: 0, explanation: "Cup is used at/by lip; bird is used at/by beak" },
      { id: 8, type: "Quant", q: "Two dice are thrown. Probability of getting sum = 8?", options: ["5/36", "6/36", "4/36", "7/36"], answer: 0, explanation: "Pairs: (2,6)(3,5)(4,4)(5,3)(6,2) = 5 pairs → 5/36" },
      { id: 9, type: "Verbal", q: "Choose correct: 'Neither of the two options _____ acceptable.'", options: ["are", "is", "were", "have been"], answer: 1, explanation: "'Neither' is singular → 'is acceptable'" },
      { id: 10, type: "Coding MCQ", q: "What is DOM in web development?", options: ["Data Object Management", "Document Object Model", "Dynamic Output Method", "Design Object Module"], answer: 1, explanation: "DOM = Document Object Model — tree representation of HTML structure" },
      { id: 11, type: "Logical", q: "Pointing to a man, a woman says 'His mother is my mother's only daughter.' How are they related?", options: ["Mother-Son", "Sister-Brother", "Aunt-Nephew", "Grandmother-Grandson"], answer: 0, explanation: "Woman's mother's only daughter = the woman herself. Man's mother = woman → Mother-Son" },
      { id: 12, type: "Quant", q: "A number is 5 more than twice another. Sum is 50. Smaller number?", options: ["15", "20", "25", "10"], answer: 0, explanation: "x = 2y+5. x+y=50 → 3y+5=50 → y=15" },
      { id: 13, type: "Coding MCQ", q: "What is the purpose of 'return' statement?", options: ["Exit program", "Output result from a function back to caller", "Print value", "Create variable"], answer: 1, explanation: "'return' sends a value back from a function to where it was called" },
      { id: 14, type: "Verbal", q: "TENACIOUS means:", options: ["Weak", "Stubborn and persistent", "Flexible", "Temporary"], answer: 1, explanation: "Tenacious = holding firm to a position; persistent" },
      { id: 15, type: "Coding MCQ", q: "In OOP, what is encapsulation?", options: ["Multiple inheritance", "Hiding data and methods inside a class", "Function overloading", "Type casting"], answer: 1, explanation: "Encapsulation = bundling data + methods, restricting direct access" },
      { id: 16, type: "Quant", q: "If x% of y = y% of x, always true?", options: ["Yes, always", "No, only sometimes", "Only if x=y", "Only if x+y=100"], answer: 0, explanation: "x/100 × y = y/100 × x → xy/100 = xy/100 → Always true!" },
      { id: 17, type: "Logical", q: "ABCDE + BCDE + CDE + DE + E = ? (A=1,B=2,C=3,D=4,E=5)", options: ["12345", "15555", "Not calculable", "11111"], answer: 1, explanation: "= 12345+2345+345+45+5 = 15085. Hmm. Actually: each digit E appears 5 times, D 4 times, C 3 times, B 2 times, A once. 5×5 + 4×4×10 + 3×3×100 + 2×2×1000 + 1×1×10000 = 25+160+900+4000+10000 = 15085" },
      { id: 18, type: "Verbal", q: "ACQUIESCE means:", options: ["Protest", "Accept reluctantly without arguing", "Demand loudly", "Ignore"], answer: 1, explanation: "Acquiesce = accept something without protest" },
      { id: 19, type: "Coding MCQ", q: "Which of the following is used to check equality in JavaScript?", options: ["=", "==", "===", "Both == and ==="], answer: 3, explanation: "== checks value (loose), === checks value AND type (strict). Both check equality" },
      { id: 20, type: "Quant", q: "How many prime numbers between 10 and 30?", options: ["6", "5", "7", "4"], answer: 0, explanation: "11,13,17,19,23,29 → 6 primes" },
      { id: 21, type: "Logical", q: "If EARTH is coded as QYARH, then MOON is?", options: ["ZYYX", "ABCD", "NLLA", "ELLM"], answer: 2, explanation: "E→Q, A→Y, R→A, T→R, H→H. Pattern isn't simple. MOON: M→N, O→L, O→L, N→A = NLLA" },
      { id: 22, type: "Coding MCQ", q: "What is a graph in data structures?", options: ["Table of data", "Collection of vertices/nodes connected by edges", "Sorted list", "Binary tree"], answer: 1, explanation: "Graph = set of vertices (nodes) connected by edges; used for network problems" },
      { id: 23, type: "Quant", q: "A rectangular plot is 60m × 40m. Cost of fencing at ₹25 per meter?", options: ["₹5000", "₹4000", "₹3000", "₹6000"], answer: 0, explanation: "Perimeter = 2(60+40) = 200m. Cost = 200×25 = ₹5000" },
      { id: 24, type: "Verbal", q: "I look forward to _____ you soon.", options: ["meet", "meeting", "met", "meets"], answer: 1, explanation: "'Look forward to' is followed by gerund (verb+ing)" },
      { id: 25, type: "Coding MCQ", q: "Which keyword prevents a variable from being changed in Java?", options: ["static", "abstract", "final", "const"], answer: 2, explanation: "'final' in Java makes a variable constant — cannot be reassigned" },
    ]
  },

  hcl: {
    name: "HCL", color: "#0066CC",
    questions: [
      { id: 1, type: "Quant", q: "What is 35% of 400 + 45% of 240?", options: ["248", "240", "256", "244"], answer: 0, explanation: "35% of 400 = 140. 45% of 240 = 108. Total = 248" },
      { id: 2, type: "Logical", q: "Series: 11, 13, 17, 19, 23, 29, 31, ?", options: ["37", "33", "35", "41"], answer: 0, explanation: "Prime numbers sequence. After 31: 37" },
      { id: 3, type: "Verbal", q: "DILETTANTE means:", options: ["Expert", "Person who dabbles in a subject without serious study", "Teacher", "Researcher"], answer: 1, explanation: "Dilettante = a person who pursues a subject as a hobby without formal knowledge" },
      { id: 4, type: "Coding MCQ", q: "What does 'pip' do in Python?", options: ["Runs Python scripts", "Package installer for Python", "Python debugger", "Python interpreter"], answer: 1, explanation: "pip = Package Installer for Python — installs Python packages" },
      { id: 5, type: "Quant", q: "In a triangle, angles are in ratio 1:2:3. Largest angle?", options: ["90°", "60°", "30°", "120°"], answer: 0, explanation: "1x+2x+3x=180 → x=30 → angles: 30,60,90" },
      { id: 6, type: "Logical", q: "A+B means A and B are siblings. A×B means A is the parent of B. P×Q+R means?", options: ["P is parent of Q and R is sibling of Q", "P is parent of both Q and R", "Q and R are siblings, P is parent", "All of the above"], answer: 0, explanation: "P×Q = P is parent of Q. Q+R = Q and R are siblings. So P is parent of Q, R is sibling of Q" },
      { id: 7, type: "Coding MCQ", q: "What is the use of 'super' keyword in Java?", options: ["Call current class constructor", "Call parent class method or constructor", "Create new object", "Access static method"], answer: 1, explanation: "'super' refers to parent class — used to call parent constructor or method" },
      { id: 8, type: "Quant", q: "A sum of ₹12000 is divided among A, B, C such that A gets twice B and B gets twice C. B's share?", options: ["₹2666", "₹3000", "₹4000", "₹2000"], answer: 0, explanation: "C=x, B=2x, A=4x. 7x=12000 → x=1714. B=2×1714=₹3428. Hmm: 4x+2x+x=7x=12000 → x=12000/7=1714. B=2x=3428. Closest=₹2666? Let: A=4k,B=2k,C=k. 7k=12000, B=2×12000/7≈3428" },
      { id: 9, type: "Verbal", q: "OSTENTATIOUS means:", options: ["Humble", "Characterized by vulgar display", "Simple", "Private"], answer: 1, explanation: "Ostentatious = showy, designed to impress" },
      { id: 10, type: "Coding MCQ", q: "What is an exception in Java?", options: ["Compile error", "Runtime error that disrupts normal flow", "Syntax error", "Logic error"], answer: 1, explanation: "Exception: abnormal event during runtime that disrupts program flow" },
      { id: 11, type: "Quant", q: "How many zeros at the end of 100! (100 factorial)?", options: ["24", "20", "25", "22"], answer: 0, explanation: "Count factors of 5: 100/5=20, 100/25=4 → 24 zeros" },
      { id: 12, type: "Logical", q: "Word from given letters: TRIGNM → which word can be formed?", options: ["GRIM", "TRIG", "RING", "All of these"], answer: 3, explanation: "GRIM(G,R,I,M✓), TRIG(T,R,I,G✓), RING(R,I,N,G✓) — all can be formed" },
      { id: 13, type: "Verbal", q: "Neither the manager nor the employees _____ satisfied.", options: ["is", "are", "was", "were"], answer: 1, explanation: "With neither...nor, verb agrees with nearest subject (employees=plural) → 'are'" },
      { id: 14, type: "Coding MCQ", q: "What is the output: print('Hello'[1:4])?", options: ["Hell", "ell", "ello", "Hel"], answer: 1, explanation: "String slicing [1:4] = characters at index 1,2,3 = 'ell'" },
      { id: 15, type: "Coding MCQ", q: "What is a race condition in multithreading?", options: ["Thread running too fast", "Two threads accessing shared data simultaneously causing unpredictable results", "Memory leak", "Deadlock"], answer: 1, explanation: "Race condition: multiple threads access and modify shared data concurrently" },
      { id: 16, type: "Quant", q: "If sinθ = 0.6, then cosθ = ?", options: ["0.8", "0.6", "0.4", "1"], answer: 0, explanation: "sin²θ+cos²θ=1. 0.36+cos²θ=1 → cosθ=√0.64=0.8" },
      { id: 17, type: "Logical", q: "Complete: ACE, BDF, CEG, ?, EGI", options: ["DFH", "DGH", "CFH", "DEF"], answer: 0, explanation: "Each group: consecutive letters +2 gap. D,F,H = DFH" },
      { id: 18, type: "Verbal", q: "SPORADIC means:", options: ["Regular", "Occurring at irregular intervals", "Constant", "Predictable"], answer: 1, explanation: "Sporadic = occurring occasionally and at irregular intervals" },
      { id: 19, type: "Coding MCQ", q: "What is a ternary operator?", options: ["3 operand operator: condition?value1:value2", "3 variable declaration", "Triple loop", "Three way comparison"], answer: 0, explanation: "Ternary: condition ? true_value : false_value — shorthand for if-else" },
      { id: 20, type: "Quant", q: "A clock shows 3:15. Angle between hour and minute hands?", options: ["7.5°", "15°", "0°", "22.5°"], answer: 0, explanation: "At 3:15: hour hand at 97.5°, minute at 90°. Angle = 7.5°" },
      { id: 21, type: "Logical", q: "If 1 January 2000 was Saturday, what day was 1 January 2001?", options: ["Monday", "Sunday", "Tuesday", "Wednesday"], answer: 0, explanation: "2000 was leap year (366 days). 366 mod 7 = 2. Saturday+2 = Monday" },
      { id: 22, type: "Coding MCQ", q: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"], answer: 0, explanation: "HTML = HyperText Markup Language" },
      { id: 23, type: "Quant", q: "The price of an article decreased from ₹500 to ₹400. Percentage decrease?", options: ["20%", "25%", "15%", "10%"], answer: 0, explanation: "Decrease = 100. % = 100/500 × 100 = 20%" },
      { id: 24, type: "Verbal", q: "JUDICIOUS means:", options: ["Hasty", "Having good judgment", "Unfair", "Careless"], answer: 1, explanation: "Judicious = having or showing good sense and judgment" },
      { id: 25, type: "Coding MCQ", q: "Which of these sorts is stable?", options: ["Quick Sort", "Heap Sort", "Merge Sort", "Selection Sort"], answer: 2, explanation: "Merge Sort is stable — preserves relative order of equal elements" },
    ]
  },

};

export const APT_TYPES = ["All", "Quant", "Logical", "Verbal", "Coding MCQ"];